--Q1 WHAT IS THE TOTAL REVENUE GENERATED BY MALE VS FEMALE CUSTOMERS?

select "Gender", sum("Purchase Amount (USD)") as revenue from customer
group by "Gender";

--Q2 WHICH CUSTOMER USED A  DISCOUNT BUT STILL SPENT MORE THAN THE AVRAGE PURCHASE AMOUNT?
select customer_id ,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer);

SELECT DISTINCT discount_applied
FROM customer;

SELECT AVG(purchase_amount)
FROM customer;

SELECT customer_id,
       purchase_amount,
       discount_applied
FROM customer
ORDER BY purchase_amount DESC;

SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount)
    FROM customer
);
--Q3 " WHICH ARE THE TOP 5 PRODUCTS WITH THE HIGHEST AVERAGE REVIEW RATING"

select item_purchased , ROUND(avg (review_rating::numeric),2)as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4 COMPARE THE AVERAGE PURCHASE AMOUNT BETWEEN STANDARD AND EXPRESS SHIPING 

select shipping_type,
ROUND(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type


--Q5 DO SUBSCRIBED CUSTOMRS SPEND MORE? COMPARE AVERAGE SPEND AND TOTAL REVENUE 
--BETWEEN SUBSCRIBERS AND NON SUBSCRIBERS.

select subscription_status,
count(customer_id) as total_customers,
ROUND(avg(purchase_amount),2) as avg_spend,
ROUND(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--Q6 WHICH 5 PRODUCTS HAVE THE HIGHEST PERCENTAGE OF PURCHASES WITH DISCOUNTS APPLIED?
select item_purchased,
ROUND(100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7 SEGMENT CUSTOMER INTO NEW ,RETURNING AND LOYAL BASED ON THEIR TOTAL 
--NUMBER OF PREVIOUS PURCHASES AND SHOW THE COUNT OF EACH SEGMENT.

with customer_type as(
select customer_id ,previous_purchases,
case
    when previous_purchases=1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
	from customer
)

select customer_segment, count(*) as "Number Of Customers"
from customer_type
group by customer_segment

--Q8 WHAT ARE THE TOP 3 MOST PURCHASED PRODUCTS WITHIN EACH CATEGORY?

with item_counts as(
select category,
item_purchased ,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc)as item_rank
from customer
group by category,item_purchased
)

select item_rank, category ,item_purchased,total_orders
from item_counts
where item_rank <= 3;

--Q9 ARE CUSTOMERS WHO ARE REPEAT BUYERS (MORE THAN 5 PREVIOUS PURCHASES) ALSO LIKELY TO SUBSCRIBE?

SELECT subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status 

--Q10 WHAT IS THE REVENUE CONTRIBUTION OF EACH AGE GROUP??

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group 
order by total_revenue desc;
